openapi: 3.0.0
info:
  title: Test APi
  version: '3.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/cheeses/{cheeseId}':
    parameters:
      - type: string
        name: cheeseId
        in: path
        required: true
    get:
      summary: get chz
      tags:
        - cheeses
      parameters:
        - schema:
            type: string
          in: header
          name: Header1
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                thing:
                  type: string
                description:
                  type: string
    post:
      summary: create chz
      tags:
        - cheeses
      responses: {}
    delete:
      summary: ''
      responses:
        '200':
          description: OK
    put:
      summary: ''
      responses:
        '200':
          description: OK
components:
  schemas: {}
