openapi: 3.0.0
info:
  title: Test APi
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/cheeses/{cheeseId}':
    parameters:
      - type: string
        name: cheeseId
        in: path
        required: true
    get:
      summary: get chz
      tags: &ref_0
        - cheeses
      responses: {}
    post:
      summary: create chz
      tags: *ref_0
      responses: {}
components:
  schemas: {}
